// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workflow-builder/Application.tsx": () => import("../components/mockups/workflow-builder/Application.tsx"),
  "./components/mockups/workflow-builder/Blueprint.tsx": () => import("../components/mockups/workflow-builder/Blueprint.tsx"),
  "./components/mockups/workflow-builder/Intake.tsx": () => import("../components/mockups/workflow-builder/Intake.tsx"),
  "./components/mockups/workflow-builder/Ledger.tsx": () => import("../components/mockups/workflow-builder/Ledger.tsx"),
  "./components/mockups/workflow-builder/Portal.tsx": () => import("../components/mockups/workflow-builder/Portal.tsx")
};
