// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homium/Backbone.tsx": () => import("../components/mockups/homium/Backbone.tsx"),
  "./components/mockups/homium/DocDimensions.tsx": () => import("../components/mockups/homium/DocDimensions.tsx"),
  "./components/mockups/homium/FormBuilderA.tsx": () => import("../components/mockups/homium/FormBuilderA.tsx"),
  "./components/mockups/homium/FormBuilderB.tsx": () => import("../components/mockups/homium/FormBuilderB.tsx"),
  "./components/mockups/homium/ReviewFilmstrip.tsx": () => import("../components/mockups/homium/ReviewFilmstrip.tsx"),
  "./components/mockups/homium/ReviewOverlay.tsx": () => import("../components/mockups/homium/ReviewOverlay.tsx"),
  "./components/mockups/homium/ReviewQueue.tsx": () => import("../components/mockups/homium/ReviewQueue.tsx"),
  "./components/mockups/workflow-builder/Application.tsx": () => import("../components/mockups/workflow-builder/Application.tsx"),
  "./components/mockups/workflow-builder/Blueprint.tsx": () => import("../components/mockups/workflow-builder/Blueprint.tsx"),
  "./components/mockups/workflow-builder/Composer.tsx": () => import("../components/mockups/workflow-builder/Composer.tsx"),
  "./components/mockups/workflow-builder/FieldNotes.tsx": () => import("../components/mockups/workflow-builder/FieldNotes.tsx"),
  "./components/mockups/workflow-builder/Flow.tsx": () => import("../components/mockups/workflow-builder/Flow.tsx"),
  "./components/mockups/workflow-builder/GardenPath.tsx": () => import("../components/mockups/workflow-builder/GardenPath.tsx"),
  "./components/mockups/workflow-builder/Intake.tsx": () => import("../components/mockups/workflow-builder/Intake.tsx"),
  "./components/mockups/workflow-builder/Ledger.tsx": () => import("../components/mockups/workflow-builder/Ledger.tsx"),
  "./components/mockups/workflow-builder/Portal.tsx": () => import("../components/mockups/workflow-builder/Portal.tsx"),
  "./components/mockups/workflow-builder/Register.tsx": () => import("../components/mockups/workflow-builder/Register.tsx"),
  "./components/mockups/workflow-builder/Schema.tsx": () => import("../components/mockups/workflow-builder/Schema.tsx"),
  "./components/mockups/homium/pages/IntakePage.tsx": () => import("../components/mockups/homium/pages/IntakePage.tsx"),
  "./components/mockups/homium/pages/RegisterPage.tsx": () => import("../components/mockups/homium/pages/RegisterPage.tsx"),
  "./components/mockups/homium/pages/TimelinePage.tsx": () => import("../components/mockups/homium/pages/TimelinePage.tsx"),
  "./components/mockups/homium/pages/WorkfilePage.tsx": () => import("../components/mockups/homium/pages/WorkfilePage.tsx")
};
